/**
 * Card data - all 36 cards with meanings in multiple languages.
 * Source: /abigail/ref_material
 */

export interface CardMeaning {
  en: string;
  de: string;
  pt: string;
  hu: string;
}

export interface Card {
  id: number;
  name: CardMeaning;  // Multilingual card names
  shortMeaning: CardMeaning;
}

// Card image name mapping (from /abigail/website/public/cards/)
const cardImageMap: Record<number, string> = {
  0: "beständigkeit", 1: "besuch", 2: "botschaft", 3: "brief", 4: "dieb",
  5: "eifersucht", 6: "etwas geld", 7: "falschheit", 8: "feind", 9: "fröhlichkeit",
  10: "Gedanke", 11: "geistlicher", 12: "geld", 13: "geliebte", 14: "geliebter",
  15: "geschenk", 16: "glück", 17: "haus", 18: "heirat", 19: "hoffnung",
  20: "kind", 21: "krankheit", 22: "liebe", 23: "offizier", 24: "reise",
  25: "richter", 26: "sehnsucht", 27: "tod", 28: "traurigkeit", 29: "treue",
  30: "unglück", 31: "unverhoffte freude", 32: "verdruss", 33: "verlust",
  34: "witwe", 35: "witwer",
};

export function getCardImageName(cardId: number): string {
  return cardImageMap[cardId] || `card_${cardId}`;
}

// All 36 cards
export const CARDS: Card[] = [
  { id: 0, name: { en: "Constancy", de: "Beständigkeit", pt: "Constância", hu: "Állandóság" }, shortMeaning: { en: '"Eye of God", means work and obligations, stability, permanence and security.', de: "'Auge von Gott', bedeutet Arbeiten und Verpflichtungen, Stabilität, Dauernhaftigkeit, Sicherheit.", pt: "'Olho de Deus', significa trabalho e obrigações, estabilidade, permanência e segurança.", hu: '"Isten szeme", munkát és kötelezettségeket, stabilitást, állandóságot és biztonságot jelent.' } },
  { id: 1, name: { en: "Visit", de: "Besuch", pt: "Visita", hu: "Látogatás" }, shortMeaning: { en: "Events, friends, parties and meetings with other people.", de: "Veranstaltungen, Freunde, Partys und allgemeine Zusammenkünfte mit anderen Menschen.", pt: "Eventos, amigos, festas e reuniões com outras pessoas.", hu: "Események, barátok, bulik és találkozások más emberekkel." } },
  { id: 2, name: { en: "Message", de: "Botschaft", pt: "Mensagem", hu: "Üzenet" }, shortMeaning: { en: "Communication, conversation.", de: "Kommunikation, Gespräche.", pt: "Comunicação, conversação.", hu: "Kommunikáció, beszélgetés." } },
  { id: 3, name: { en: "Letter", de: "Brief", pt: "Carta", hu: "Levél" }, shortMeaning: { en: "This card shows an important message, which can be a phone call, email, letter, or important document. It can also mean an invitation, secret or contract.", de: "Diese Karte zeigt eine wichtige Mitteilung (Telefon, eine E-Mail oder einen Brief, Schriftstücke und Dokumente), Einladung, Geheimnis, Vertrag.", pt: "Esta carta mostra uma mensagem importante, que pode ser um telefonema, E-Mail, carta, ou documento importante. Além disso pode significar um convite, segredo ou contrato.", hu: "Ez a kártya fontos üzenetet mutat, amely lehet telefonhívás, e-mail, levél vagy fontos dokumentum. Jelenthet meghívást, titkot vagy szerződést is." } },
  { id: 4, name: { en: "Thief", de: "Dieb", pt: "Ladrão", hu: "Tolvaj" }, shortMeaning: { en: "This card shows negative influences and tension generated by other people. If this card is near a card representing a person, it means you should be careful with them.", de: "Diese Karte zeigt negative Einflüsse und Belastungen, die durch andere Personen verursacht werden. In der Nähe einer Personenkarte gibt sie immer den Hinweis, dass Du Dich vor dieser Person in Acht nehmen solltest.", pt: "Esta carta mostra influências negativas e tensão geradas por outras pessoas. Se esta carta está próxima de uma carta representando uma pessoa, significa então que você deve tomar cuidado com ela.", hu: "Ez a kártya más emberek által generált negatív befolyásokat és feszültséget mutat. Ha ez a kártya egy személyt ábrázoló kártya közelében van, azt jelenti, hogy óvatosnak kell lenned vele." } },
  { id: 5, name: { en: "Jealousy", de: "Eifersucht", pt: "Ciúme", hu: "Féltékenység" }, shortMeaning: { en: "Envy, jealousy and distrust.", de: "Neid, Missgunst und Misstrauen.", pt: "Inveja, 'olho gordo' e desconfiança.", hu: "Irigység, féltékenység és bizalmatlanság." } },
  { id: 6, name: { en: "Some Money", de: "Etwas Geld", pt: "Algum Dinheiro", hu: "Kevés Pénz" }, shortMeaning: { en: "This card shows a smaller amount of money.", de: "Diese Karte zeigt eine kleinere Geldsumme.", pt: "Essa carta mostra uma pequena quantidade de dinheiro.", hu: "Ez a kártya egy kisebb pénzösszeget mutat." } },
  { id: 7, name: { en: "Falsehood", de: "Falschheit", pt: "Falsidade", hu: "Hamisság" }, shortMeaning: { en: "This card shows that something false and unjust is happening in your environment. It also warns of mistakes and misfortunes that may occur to you or those around you. If this card is near a person card, it means that person is dishonest.", de: "Diese Karte zeigt, dass etwas Falsches und Ungerechtes in deiner Umgebung passiert. Sie warnt auch vor Fehlern und Unglücken, die dir oder deinen Mitmenschen widerfahren können. In der Nähe einer Personenkarte bedeutet sie, dass diese Person unehrlich ist.", pt: "Esta carta mostra que algo falso e injusto está acontecendo em seu ambiente. Também adverte sobre erros e infortúnios que podem ocorrer a você ou àqueles ao seu redor. Se esta carta está próxima de uma carta de pessoa, significa que essa pessoa é desonesta.", hu: "Ez a kártya azt mutatja, hogy valami hamis és igazságtalan dolog történik a környezetedben. Figyelmeztet hibákra és szerencsétlenségekre is, amelyek veled vagy körülötted lévőkkel történhetnek. Ha ez a kártya egy személykártya közelében van, azt jelenti, hogy az a személy becstelen." } },
  { id: 8, name: { en: "Enemy", de: "Feind", pt: "Inimigo", hu: "Ellenség" }, shortMeaning: { en: "This card shows an enemy or someone who wishes you harm. It can also mean conflicts, disputes, or legal problems.", de: "Diese Karte zeigt einen Feind oder jemanden, der dir schaden möchte. Sie kann auch Konflikte, Streitigkeiten oder rechtliche Probleme bedeuten.", pt: "Esta carta mostra um inimigo ou alguém que deseja te fazer mal. Também pode significar conflitos, disputas ou problemas legais.", hu: "Ez a kártya ellenséget vagy valakit mutat, aki kárt akar neked. Jelenthet konfliktusokat, vitákat vagy jogi problémákat is." } },
  { id: 9, name: { en: "Joy", de: "Fröhlichkeit", pt: "Alegria", hu: "Öröm" }, shortMeaning: { en: "Happiness, joy, celebration and positive events.", de: "Freude, Glück, Feiern und positive Ereignisse.", pt: "Felicidade, alegria, celebração e eventos positivos.", hu: "Boldogság, öröm, ünneplés és pozitív események." } },
  { id: 10, name: { en: "Thought", de: "Gedanke", pt: "Pensamento", hu: "Gondolat" }, shortMeaning: { en: "Thoughts, ideas, plans and mental processes.", de: "Gedanken, Ideen, Pläne und mentale Prozesse.", pt: "Pensamentos, ideias, planos e processos mentais.", hu: "Gondolatok, ötletek, tervek és mentális folyamatok." } },
  { id: 11, name: { en: "Priest", de: "Geistlicher", pt: "Sacerdote", hu: "Pap" }, shortMeaning: { en: "Spiritual guidance, wisdom, or an older man as a person card (father, grandfather, uncle, older brother, or older friend).", de: "Spirituelle Führung, Weisheit, oder als Personenkarte ein älterer Mann (Vater, Großvater, Onkel, älterer Bruder oder älterer Freund).", pt: "Orientação espiritual, sabedoria, ou como carta de pessoa, um homem mais velho (pai, avô, tio, irmão mais velho ou amigo mais velho).", hu: "Spirituális vezetés, bölcsesség, vagy személykártyaként egy idősebb férfi (apa, nagyapa, nagybátya, idősebb testvér vagy idősebb barát)." } },
  { id: 12, name: { en: "Money", de: "Geld", pt: "Dinheiro", hu: "Pénz" }, shortMeaning: { en: "This card shows a larger amount of money or financial gain.", de: "Diese Karte zeigt eine größere Geldsumme oder finanziellen Gewinn.", pt: "Esta carta mostra uma quantidade maior de dinheiro ou ganho financeiro.", hu: "Ez a kártya egy nagyobb pénzösszeget vagy pénzügyi nyereséget mutat." } },
  { id: 13, name: { en: "Beloved Woman", de: "Geliebte", pt: "Amada", hu: "Szeretett Nő" }, shortMeaning: { en: "A beloved person, romantic partner, or close relationship.", de: "Ein geliebter Mensch, romantischer Partner oder enge Beziehung.", pt: "Uma pessoa amada, parceiro romântico ou relacionamento próximo.", hu: "Egy szeretett személy, romantikus partner vagy közeli kapcsolat." } },
  { id: 14, name: { en: "Beloved Man", de: "Geliebter", pt: "Amado", hu: "Szeretett Férfi" }, shortMeaning: { en: "Love, romance and deep emotional connection.", de: "Liebe, Romantik und tiefe emotionale Verbindung.", pt: "Amor, romance e conexão emocional profunda.", hu: "Szerelem, romantika és mély érzelmi kapcsolat." } },
  { id: 15, name: { en: "Gift", de: "Geschenk", pt: "Presente", hu: "Ajándék" }, shortMeaning: { en: "A gift, surprise, or unexpected positive event.", de: "Ein Geschenk, Überraschung oder unerwartetes positives Ereignis.", pt: "Um presente, surpresa ou evento positivo inesperado.", hu: "Ajándék, meglepetés vagy váratlan pozitív esemény." } },
  { id: 16, name: { en: "Luck", de: "Glück", pt: "Sorte", hu: "Szerencse" }, shortMeaning: { en: "Good luck, fortune and positive outcomes.", de: "Glück, Glücksfall und positive Ergebnisse.", pt: "Boa sorte, fortuna e resultados positivos.", hu: "Szerencse, szerencsés esemény és pozitív eredmények." } },
  { id: 17, name: { en: "House", de: "Haus", pt: "Casa", hu: "Ház" }, shortMeaning: { en: "Home, family, stability and security.", de: "Zuhause, Familie, Stabilität und Sicherheit.", pt: "Casa, família, estabilidade e segurança.", hu: "Otthon, család, stabilitás és biztonság." } },
  { id: 18, name: { en: "Marriage", de: "Heirat", pt: "Casamento", hu: "Házasság" }, shortMeaning: { en: "Marriage, partnership, commitment and union.", de: "Heirat, Partnerschaft, Engagement und Vereinigung.", pt: "Casamento, parceria, compromisso e união.", hu: "Házasság, partnerség, elköteleződés és egyesülés." } },
  { id: 19, name: { en: "Hope", de: "Hoffnung", pt: "Esperança", hu: "Remény" }, shortMeaning: { en: "Hope, optimism and positive expectations.", de: "Hoffnung, Optimismus und positive Erwartungen.", pt: "Esperança, otimismo e expectativas positivas.", hu: "Remény, optimizmus és pozitív elvárások." } },
  { id: 20, name: { en: "Child", de: "Kind", pt: "Criança", hu: "Gyermek" }, shortMeaning: { en: "A child, new beginnings, innocence, or creativity.", de: "Ein Kind, neue Anfänge, Unschuld oder Kreativität.", pt: "Uma criança, novos começos, inocência ou criatividade.", hu: "Egy gyermek, új kezdetek, ártatlanság vagy kreativitás." } },
  { id: 21, name: { en: "Illness", de: "Krankheit", pt: "Doença", hu: "Betegség" }, shortMeaning: { en: "Health issues, physical or emotional challenges.", de: "Gesundheitsprobleme, körperliche oder emotionale Herausforderungen.", pt: "Problemas de saúde, desafios físicos ou emocionais.", hu: "Egészségügyi problémák, fizikai vagy érzelmi kihívások." } },
  { id: 22, name: { en: "Love", de: "Liebe", pt: "Amor", hu: "Szerelem" }, shortMeaning: { en: "Love, romance and deep emotional connection.", de: "Liebe, Romantik und tiefe emotionale Verbindung.", pt: "Amor, romance e conexão emocional profunda.", hu: "Szerelem, romantika és mély érzelmi kapcsolat." } },
  { id: 23, name: { en: "Officer", de: "Offizier", pt: "Oficial", hu: "Tiszt" }, shortMeaning: { en: "Authority, leadership, or a person in a position of power.", de: "Autorität, Führung oder eine Person in einer Machtposition.", pt: "Autoridade, liderança ou uma pessoa em posição de poder.", hu: "Tekintély, vezetés vagy hatalmi pozícióban lévő személy." } },
  { id: 24, name: { en: "Journey", de: "Reise", pt: "Viagem", hu: "Utazás" }, shortMeaning: { en: "Travel, movement, change of location or life journey.", de: "Reise, Bewegung, Ortswechsel oder Lebensreise.", pt: "Viagem, movimento, mudança de localização ou jornada de vida.", hu: "Utazás, mozgás, helyváltoztatás vagy életút." } },
  { id: 25, name: { en: "Judge", de: "Richter", pt: "Juiz", hu: "Bíró" }, shortMeaning: { en: "Justice, legal matters, decisions and judgment.", de: "Gerechtigkeit, rechtliche Angelegenheiten, Entscheidungen und Urteil.", pt: "Justiça, questões legais, decisões e julgamento.", hu: "Igazság, jogi ügyek, döntések és ítélet." } },
  { id: 26, name: { en: "Longing", de: "Sehnsucht", pt: "Saudade", hu: "Vágyakozás" }, shortMeaning: { en: "Longing, desire, yearning for something or someone.", de: "Sehnsucht, Verlangen, Sehnen nach etwas oder jemandem.", pt: "Saudade, desejo, anseio por algo ou alguém.", hu: "Vágyakozás, vágy, sóvárgás valami vagy valaki után." } },
  { id: 27, name: { en: "Death", de: "Tod", pt: "Morte", hu: "Halál" }, shortMeaning: { en: "Endings, transformation, or significant change.", de: "Enden, Transformation oder bedeutende Veränderung.", pt: "Fins, transformação ou mudança significativa.", hu: "Végek, átalakulás vagy jelentős változás." } },
  { id: 28, name: { en: "Sadness", de: "Traurigkeit", pt: "Tristeza", hu: "Szomorúság" }, shortMeaning: { en: "Sadness, grief, emotional pain or disappointment.", de: "Traurigkeit, Trauer, emotionaler Schmerz oder Enttäuschung.", pt: "Tristeza, luto, dor emocional ou decepção.", hu: "Szomorúság, gyász, érzelmi fájdalom vagy csalódás." } },
  { id: 29, name: { en: "Fidelity", de: "Treue", pt: "Fidelidade", hu: "Hűség" }, shortMeaning: { en: "Loyalty, faithfulness, trust and commitment.", de: "Loyalität, Treue, Vertrauen und Engagement.", pt: "Lealdade, fidelidade, confiança e compromisso.", hu: "Hűség, lojalitás, bizalom és elköteleződés." } },
  { id: 30, name: { en: "Misfortune", de: "Unglück", pt: "Infortúnio", hu: "Szerencsétlenség" }, shortMeaning: { en: "Bad luck, misfortune, negative events or obstacles.", de: "Pech, Unglück, negative Ereignisse oder Hindernisse.", pt: "Má sorte, infortúnio, eventos negativos ou obstáculos.", hu: "Balszerencse, szerencsétlenség, negatív események vagy akadályok." } },
  { id: 31, name: { en: "Unexpected Joy", de: "Unverhoffte Freude", pt: "Alegria Inesperada", hu: "Váratlan Öröm" }, shortMeaning: { en: "Unexpected joy, pleasant surprise or sudden happiness.", de: "Unerwartete Freude, angenehme Überraschung oder plötzliches Glück.", pt: "Alegria inesperada, surpresa agradável ou felicidade súbita.", hu: "Váratlan öröm, kellemes meglepetés vagy hirtelen boldogság." } },
  { id: 32, name: { en: "Vexation", de: "Verdruss", pt: "Aborrecimento", hu: "Bosszúság" }, shortMeaning: { en: "Annoyance, frustration, irritation or worry.", de: "Ärger, Frustration, Irritation oder Sorge.", pt: "Irritação, frustração, aborrecimento ou preocupação.", hu: "Bosszúság, frusztráció, irritáció vagy aggodalom." } },
  { id: 33, name: { en: "Loss", de: "Verlust", pt: "Perda", hu: "Veszteség" }, shortMeaning: { en: "Loss, separation, letting go or material loss.", de: "Verlust, Trennung, Loslassen oder materieller Verlust.", pt: "Perda, separação, desapego ou perda material.", hu: "Veszteség, szétválás, elengedés vagy anyagi veszteség." } },
  { id: 34, name: { en: "Widow", de: "Witwe", pt: "Viúva", hu: "Özvegy Nő" }, shortMeaning: { en: "A woman, often older, or representing solitude and independence.", de: "Eine Frau, oft älter, oder Einsamkeit und Unabhängigkeit darstellend.", pt: "Uma mulher, frequentemente mais velha, ou representando solidão e independência.", hu: "Egy nő, gyakran idősebb, vagy magányt és függetlenséget képviselő." } },
  { id: 35, name: { en: "Widower", de: "Witwer", pt: "Viúvo", hu: "Özvegy Férfi" }, shortMeaning: { en: "Calm and loneliness. Mostly, however, it shows an older man as a person card. It can be the father, grandfather, uncle, older brother, or older friend.", de: "Ruhe und Einsamkeit. Meistens zeigt sie jedoch als Personenkarte einen älteren Mann. Es kann sich um den Vater, Großvater, Onkel, älteren Bruder, oder älteren Freund handeln.", pt: "Calma e solidão. Representa, como carta de pessoa, um homem mais velho, podendo ser o pai, avô, tio, irmão mais velho ou parceiro mais velho.", hu: "Nyugalom és magány. Legtöbbször azonban egy idősebb férfit ábrázol személykártyaként. Lehet az apa, nagyapa, nagybátya, idősebb testvér vagy idősebb barát." } },
];

export function getCard(cardId: number): Card | undefined {
  return CARDS.find(c => c.id === cardId);
}

export function getCards(cardIds: number[]): Card[] {
  return cardIds.map(id => getCard(id)).filter((c): c is Card => c !== undefined);
}


