"""
Card data definitions.
Contains all 36 cards with their meanings in multiple languages.
"""
from typing import Dict, TypedDict


class CardMeaning(TypedDict):
    """Card meaning in multiple languages."""
    en: str
    de: str
    pt: str
    hu: str


class Card:
    """Represents a single oracle card."""
    def __init__(self, id: int, name_key: str, short_meaning: CardMeaning):
        self.id = id
        self.name_key = name_key
        self.short_meaning = short_meaning


# All 36 cards with meanings in EN, DE, PT, HU
CARDS: Dict[int, Card] = {
    0: Card(
        0,
        "constancy",
        {
            "en": '"Eye of God", means work and obligations, stability, permanence and security.',
            "de": "'Auge von Gott', bedeutet Arbeiten und Verpflichtungen, Stabilität, Dauernhaftigkeit, Sicherheit.",
            "pt": "'Olho de Deus', significa trabalho e obrigações, estabilidade, permanência e segurança.",
            "hu": '"Isten szeme", munkát és kötelezettségeket, stabilitást, állandóságot és biztonságot jelent.',
        },
    ),
    1: Card(
        1,
        "visit",
        {
            "en": "Events, friends, parties and meetings with other people.",
            "de": "Veranstaltungen, Freunde, Partys und allgemeine Zusammenkünfte mit anderen Menschen.",
            "pt": "Eventos, amigos, festas e reuniões com outras pessoas.",
            "hu": "Események, barátok, bulik és találkozások más emberekkel.",
        },
    ),
    2: Card(
        2,
        "message",
        {
            "en": "Communication, conversation.",
            "de": "Kommunikation, Gespräche.",
            "pt": "Comunicação, conversação.",
            "hu": "Kommunikáció, beszélgetés.",
        },
    ),
    3: Card(
        3,
        "letter",
        {
            "en": "This card shows an important message, which can be a phone call, email, letter, or important document. It can also mean an invitation, secret or contract.",
            "de": "Diese Karte zeigt eine wichtige Mitteilung (Telefon, eine E-Mail oder einen Brief, Schriftstücke und Dokumente), Einladung, Geheimnis, Vertrag.",
            "pt": "Esta carta mostra uma mensagem importante, que pode ser um telefonema, E-Mail, carta, ou documento importante. Além disso pode significar um convite, segredo ou contrato.",
            "hu": "Ez a kártya fontos üzenetet mutat, amely lehet telefonhívás, e-mail, levél vagy fontos dokumentum. Jelenthet meghívást, titkot vagy szerződést is.",
        },
    ),
    4: Card(
        4,
        "thief",
        {
            "en": "This card shows negative influences and tension generated by other people. If this card is near a card representing a person, it means you should be careful with them.",
            "de": "Diese Karte zeigt negative Einflüsse und Belastungen, die durch andere Personen verursacht werden. In der Nähe einer Personenkarte gibt sie immer den Hinweis, dass Du Dich vor dieser Person in Acht nehmen solltest.",
            "pt": "Esta carta mostra influências negativas e tensão geradas por outras pessoas. Se esta carta está próxima de uma carta representando uma pessoa, significa então que você deve tomar cuidado com ela.",
            "hu": "Ez a kártya más emberek által generált negatív befolyásokat és feszültséget mutat. Ha ez a kártya egy személyt ábrázoló kártya közelében van, azt jelenti, hogy óvatosnak kell lenned vele.",
        },
    ),
    5: Card(
        5,
        "jealousy",
        {
            "en": "Envy, jealousy and distrust.",
            "de": "Neid, Missgunst und Misstrauen.",
            "pt": "Inveja, 'olho gordo' e desconfiança.",
            "hu": "Irigység, féltékenység és bizalmatlanság.",
        },
    ),
    6: Card(
        6,
        "someMoney",
        {
            "en": "This card shows a smaller amount of money.",
            "de": "Diese Karte zeigt eine kleinere Geldsumme.",
            "pt": "Essa carta mostra uma pequena quantidade de dinheiro.",
            "hu": "Ez a kártya egy kisebb pénzösszeget mutat.",
        },
    ),
    7: Card(
        7,
        "falsehood",
        {
            "en": "This card shows that something false and unjust is happening in your environment. It also warns of mistakes and misfortunes that may occur to you or those around you. If this card is near a person card, it means that person is dishonest.",
            "de": "Diese Karte zeigt an, dass in Deinem Umfeld einiges falsch und ungerecht verläuft. Auch warnt sie vor Fehlern und Missgeschicken, die Dir oder Deinen Mitmenschen unterlaufen. In der Nähe einer Personenkarte sagt sie aus, dass die Person unehrlich ist.",
            "pt": "Essa carta mostra que algo falso e injusto ocorre em seu meio social. Ela também alerta para erros e infortúnios que possam ocorrer a você ou a seus próximos. Se esta carta se localiza próxima a uma carta de pessoa, significa que se trata de uma pessoa desonesta.",
            "hu": "Ez a kártya azt mutatja, hogy valami hamis és igazságtalan történik a környezetedben. Figyelmeztet hibákra és balszerencsékre is, amelyek veled vagy környezeteddel történhetnek. Ha ez a kártya egy személykártya közelében van, azt jelenti, hogy az illető nem őszinte.",
        },
    ),
    8: Card(
        8,
        "enemy",
        {
            "en": "This card indicates that you have enemies in your social circle who want to harm you. It also shows revenge and moral rejection, suggesting caution.",
            "de": "Diese Karte besagt, dass Du in Deinem Umfeld Feinde hast, die es mit Dir nicht gut meinen und Dir schaden wollen. Aber auch Rache und moralische Verwerfungen werden angezeigt und raten deshalb zur Vorsicht.",
            "pt": "Essa carta indica que você tem inimigos no seu círculo social, que querem prejudicá-lo(a). Também vingança e rejeição moral são mostrados pela carta, que sugere cuidado.",
            "hu": "Ez a kártya azt jelzi, hogy vannak ellenségeid a társasági körödben, akik ártani akarnak neked. Bosszút és erkölcsi elutasítást is mutat, óvatosságra intve.",
        },
    ),
    9: Card(
        9,
        "joy",
        {
            "en": "Joyful time with many positive surprises.",
            "de": "Fröhliche Zeit, mit vielen positiven Überraschungen.",
            "pt": "Tempo alegre com muitas surpresas positivas.",
            "hu": "Örömteli időszak sok pozitív meglepetéssel.",
        },
    ),
    10: Card(
        10,
        "thought",
        {
            "en": "Plans and thoughts. It also represents a person card, symbolizing a younger, thoughtful and mostly somewhat introverted man from your environment.",
            "de": "Pläne und Gedanken. Auch stellt sie eine Personenkarte dar und symbolisiert einen jüngeren, nachdenklichen und meist etwas introvertierten Mann, der aus Deinem Umfeld kommt.",
            "pt": "Planos e pensamentos. Também simboliza uma pessoa de seu círculo social - um homem jovem, pensativo e um pouco introvertido.",
            "hu": "Tervek és gondolatok. Személykártyaként is szolgál, egy fiatalabb, gondolkodó és többnyire kissé introvertált férfit szimbolizál a környezetedből.",
        },
    ),
    11: Card(
        11,
        "priest",
        {
            "en": "This card symbolizes esotericism, religion, life philosophy and worldview. Near a person card, it always indicates that the person has much mercy, social understanding and compassion.",
            "de": "Diese Karte symbolisiert Esoterik, Religion, Lebensphilosophie und Weltanschauung. In der Nähe einer Personenkarte sagt sie immer aus, dass die Person viel Barmherzigkeit, soziales Verständnis und Mitgefühl hat.",
            "pt": "Essa carta simboliza esoterismo, religião, filosofia de vida e visão de mundo. Próxima a uma carta de pessoa, essa carta indica sempre que essa pessoa é especialmente misericordiosa e compreensiva.",
            "hu": "Ez a kártya az ezoterikát, vallást, életfilozófiát és világnézetet szimbolizálja. Egy személykártya közelében mindig azt jelzi, hogy az illető nagyon kegyelmes, társadalmilag megértő és együttérző.",
        },
    ),
    12: Card(
        12,
        "money",
        {
            "en": "Money and wealth.",
            "de": "Geld und Wohlstand.",
            "pt": "Dinheiro e Bem-Estar.",
            "hu": "Pénz és jólét.",
        },
    ),
    13: Card(
        13,
        "beloved",
        {
            "en": "This card is a person card. A man is represented as the Beloved card and a woman as the Beloved card. If the man or woman has a secret love besides the existing partnership, this is represented as another person card. All cards above the main person show their thoughts, and the cards below show their possessions or current everyday situation.",
            "de": "Diese Karte ist eine Personenkarte. Ein Mann wird als die Karte Geliebter und eine Frau als die Karte Geliebte dargestellt. Hat der Mann oder die Frau neben der bestehenden Partnerschaft noch eine heimliche Liebe, wird diese als eine weitere Personenkarte dargestellt. Alle Karten, die über der Hauptperson liegen, zeigen deren Gedanken und die darunter liegenden Karten deren Besitz oder die gegenwärtige Alltagssituation.",
            "pt": "Esta carta é uma carta que representa uma pessoa, podendo ser um homem ou uma mulher. No caso do homem ou mulher ter um caso fora de seu relacionamento, isso será representado por uma carta de pessoa adicional. Todas as cartas que se localizam sobre a carta principal mostram os pensamentos dessa pessoa. Já as cartas que se localizam abaixo da carta principal representam posse ou situação atual.",
            "hu": "Ez a kártya egy személykártya. Egy férfi a Kedves kártyaként, egy nő szintén a Kedves kártyaként jelenik meg. Ha a férfinak vagy nőnek a meglévő kapcsolaton kívül titkos szerelme van, azt egy másik személykártya ábrázolja. A főszemély feletti kártyák a gondolatait mutatják, az alatta lévők a birtokait vagy jelenlegi mindennapi helyzetét.",
        },
    ),
    14: Card(
        14,
        "beloved",
        {
            "en": "This card is a person card. A man is represented as the Beloved card and a woman as the Beloved card. If the man or woman has a secret love besides the existing partnership, this is represented as another person card. All cards above the main person show their thoughts, and the cards below show their possessions or current everyday situation.",
            "de": "Diese Karte ist eine Personenkarte. Ein Mann wird als die Karte Geliebter und eine Frau als die Karte Geliebte dargestellt. Hat der Mann oder die Frau neben der bestehenden Partnerschaft noch eine heimliche Liebe, wird diese als eine weitere Personenkarte dargestellt. Alle Karten, die über der Hauptperson liegen, zeigen deren Gedanken und die darunter liegenden Karten deren Besitz oder die gegenwärtige Alltagssituation.",
            "pt": "Esta carta é uma carta que representa uma pessoa, podendo ser um homem ou uma mulher. No caso do homem ou mulher ter um caso fora de seu relacionamento, isso será representado por uma carta de pessoa adicional. Todas as cartas que se localizam sobre a carta principal mostram os pensamentos dessa pessoa. Já as cartas que se localizam abaixo da carta principal representam posse ou situação atual.",
            "hu": "Ez a kártya egy személykártya. Egy férfi a Kedves kártyaként, egy nő szintén a Kedves kártyaként jelenik meg. Ha a férfinak vagy nőnek a meglévő kapcsolaton kívül titkos szerelme van, azt egy másik személykártya ábrázolja. A főszemély feletti kártyák a gondolatait mutatják, az alatta lévők a birtokait vagy jelenlegi mindennapi helyzetét.",
        },
    ),
    15: Card(
        15,
        "gift",
        {
            "en": "This card symbolizes not only gifts, but also positive events that require your attention. Near a person card, it says that the person has a special talent.",
            "de": "Diese Zigeunerkarte symbolisiert nicht nur Geschenke, sondern auch positive Ereignisse, denen Du Deine Aufmerksamkeit schenkst. Meistens wird mit ihr aber eine Begabung angezeigt. In der Nähe einer Personenkarte sagt sie aus, dass die Person ein besonderes Talent hat.",
            "pt": "Esta carta simboliza não apenas um presente, mas também eventos positivos, que requerem sua atenção. Próxima a uma carta de pessoa, esta carta diz que a pessoa tem um talento especial.",
            "hu": "Ez a kártya nemcsak ajándékokat szimbolizál, hanem pozitív eseményeket is, amelyek figyelmedet igénylik. Egy személykártya közelében azt mondja, hogy az illetőnek különleges tehetsége van.",
        },
    ),
    16: Card(
        16,
        "fortune",
        {
            "en": "This card symbolizes fortune, a time of luck and great success. Should negative cards be nearby, they will be weakened by the positive statement of the fortune card. Near a person card, it says that the person is optimistic and blessed with luck.",
            "de": "Diese Karte symbolisiert das Glück, eine glückliche Zeit und den großen Erfolg. Sollten negative Karten dabei liegen, werden diese durch die positive Aussage der Glückskarte abgeschwächt und fallen deswegen bei der Deutung nicht mehr so stark ins Gewicht. In der Nähe einer Personenkarte sagt sie aus, dass die Person optimistisch und vom Glück verwöhnt ist.",
            "pt": "Essa carta simboliza a fortuna, um tempo de sorte e grande sucesso. Caso hajam cartas negativas na proximidade dessa carta, o efeito delas será abrandado pela carta de fortuna. Caso esta carta esteja próxima a uma carta de pessoa, ela indica que essa é uma pessoa otimista e de sorte.",
            "hu": "Ez a kártya a szerencsét, szerencsés időszakot és nagy sikert szimbolizálja. Ha negatív kártyák vannak a közelben, azokat a szerencsekártya pozitív állítása gyengíti. Egy személykártya közelében azt mondja, hogy az illető optimista és szerencsés.",
        },
    ),
    17: Card(
        17,
        "house",
        {
            "en": "House, apartment or property, own family or the living environment.",
            "de": "Haus, Wohnung oder Grundstück, eigene Familie oder das wohnliche Umfeld.",
            "pt": "Casa, apartamento ou terreno, própria família ou ambiente em que se habita.",
            "hu": "Ház, lakás vagy ingatlan, saját család vagy a lakóhely környezete.",
        },
    ),
    18: Card(
        18,
        "marriage",
        {
            "en": "The card symbolizes a stable relationship or bond. Near a person card, it says that the person is faithful and reliable.",
            "de": "Die Karte symbolisiert eine feste Beziehung oder Bindung. In der Nähe einer Personenkarte sagt sie aus, dass die Person treu und zuverlässig ist.",
            "pt": "A carta simboliza um relacionamento estável. Se estiver próxima a uma carta de pessoa, a carta indica que essa pessoa é fiel e confiável.",
            "hu": "A kártya stabil kapcsolatot vagy köteléket szimbolizál. Egy személykártya közelében azt mondja, hogy az illető hűséges és megbízható.",
        },
    ),
    19: Card(
        19,
        "hope",
        {
            "en": "This card shows positive thoughts and wishes and indicates that a matter is turning for the better.",
            "de": "Diese Karte zeigt positive Gedanken und Wünsche und besagt, dass sich eine Angelegenheit zum Guten wendet.",
            "pt": "Essa carta mostra pensamentos e desejos positivos, além disso mostra uma mudança para o bem.",
            "hu": "Ez a kártya pozitív gondolatokat és kívánságokat mutat, és azt jelzi, hogy egy ügy a jobbra fordul.",
        },
    ),
    20: Card(
        20,
        "child",
        {
            "en": "The card shows a small child. It also symbolizes news, renewals or a new beginning.",
            "de": "Die Karte zeigt ein kleines Kind. Auch symbolisiert sie Neuigkeiten, Erneuerungen oder einen Neubeginn.",
            "pt": "A carta mostra uma criança pequena e simboliza novidades, renovações ou um novo começo.",
            "hu": "A kártya egy kis gyereket mutat. Új híreket, megújulásokat vagy új kezdetet is szimbolizál.",
        },
    ),
    21: Card(
        21,
        "illness",
        {
            "en": "Physical or mental illness. Lack in relationship or material damage.",
            "de": "Körperliche oder seelische Krankheit. Mangel in Beziehung oder materielle Schaden.",
            "pt": "Doença física ou psíquica. Carência no relacionamento ou danos materiais.",
            "hu": "Fizikai vagy lelki betegség. Hiány a kapcsolatban vagy anyagi kár.",
        },
    ),
    22: Card(
        22,
        "love",
        {
            "en": "Love, harmony and tenderness. If not directly asked about love, it shows near another card that the matter ends well. Near a person card, it says that the person is very warm-hearted and lovable.",
            "de": "Liebe, Harmonie und Zärtlichkeit. Wird nicht direkt nach der Liebe gefragt, zeigt sie in der Nähe einer anderen Karte, dass die Angelegenheit ein gutes Ende nimmt. In der Nähe einer Personenkarte sagt sie aus, dass die Person sehr herzlich und liebenswürdig ist.",
            "pt": "Amor, harmonia e afeto. Caso a pergunta não seja diretamente ligada ao Amor, a carta mostra um final feliz em um determinado tema. Se próxima a uma carta de pessoa, ela mostra que essa pessoa é afetuosa e amável.",
            "hu": "Szerelem, harmónia és gyengédség. Ha nem közvetlenül a szerelemről kérdeznek, egy másik kártya közelében azt mutatja, hogy az ügy jól végződik. Egy személykártya közelében azt mondja, hogy az illető nagyon szíves és szerethető.",
        },
    ),
    23: Card(
        23,
        "officer",
        {
            "en": "This card shows a man who is influential or has dominant and authoritarian behavior. This can be a friend or a young male relative. It also symbolizes authorities and officials with whom you are confronted in everyday life.",
            "de": "Diese Karte zeigt einen Mann, der einflussreich ist oder ein dominantes und autoritäres Verhalten aufweist. Hierbei kann es sich um einen Freund oder einen jungen männlichen Verwandten handeln. Auch symbolisiert sie Behörden und Amtspersonen, mit denen Du im Alltag konfrontiert wirst.",
            "pt": "Essa carta mostra um homem influente ou de comportamento autoritário. A carta pode representar um amigo ou um parente jovem. Além disso ela representa uma autoridade pública ou oficial, com o qual você será confrontado no cotidiano.",
            "hu": "Ez a kártya egy befolyásos férfit mutat, aki domináns és tekintélyelvű viselkedést mutat. Ez lehet barát vagy fiatal férfi rokon. Hatóságokat és hivatalnokokat is szimbolizál, akikkel a mindennapi életben találkozol.",
        },
    ),
    24: Card(
        24,
        "journey",
        {
            "en": "The card symbolizes a journey or means of transportation or changes.",
            "de": "Die Karte symbolisiert eine Reise oder ein Fortbewegungsmittel oder Änderungen.",
            "pt": "Essa carta simboliza uma viagem, meio de locomoção ou uma mudança.",
            "hu": "A kártya utazást, közlekedési eszközt vagy változásokat szimbolizál.",
        },
    ),
    25: Card(
        25,
        "judge",
        {
            "en": "This card symbolizes all decisions that are yet to be made in the near future. Depending on the question, it also shows legal persons or the court.",
            "de": "Diese Karte symbolisiert alle Entscheidungen, die in der nächsten Zeit noch zu treffen sind. Je nach Frage zeigt sie aber auch juristische Personen oder auch das Gericht an.",
            "pt": "Essa carta simboliza todas as decisões que devem ser tomadas no futuro próximo. Dependendo da pergunta a carta também pode representar pessoas jurídicas ou um tribunal.",
            "hu": "Ez a kártya az összes döntést szimbolizálja, amelyeket a közeljövőben még meg kell hozni. A kérdéstől függően jogi személyeket vagy a bíróságot is mutatja.",
        },
    ),
    26: Card(
        26,
        "longing",
        {
            "en": "This card symbolizes wishes and dreams that are very difficult to fulfill. It indicates that much patience is required for the fulfillment of wishes. Near a person card, it says that the person is extremely demanding.",
            "de": "Diese Karte symbolisiert Wünsche und Träume, die sehr schwer in Erfüllung gehen. Sie gibt den Hinweis, dass für die Wunscherfüllung viel Geduld erforderlich ist. In der Nähe einer Personenkarte sagt sie aus, dass die Person äußerst anspruchsvoll ist.",
            "pt": "Esta carta simboliza desejos e sonhos difíceis de realizar e adverte que, para a realização dos mesmos, muita paciência será necessária. Se esta carta estiver próxima a uma carta de pessoa, ela indica que essa é uma pessoa exigente.",
            "hu": "Ez a kártya olyan kívánságokat és álmokat szimbolizál, amelyeket nagyon nehéz teljesíteni. Azt jelzi, hogy sok türelem szükséges a kívánságok teljesítéséhez. Egy személykártya közelében azt mondja, hogy az illető rendkívül igényes.",
        },
    ),
    27: Card(
        27,
        "death",
        {
            "en": "The card shows that a situation or a phase of life comes to an end. It also symbolizes bad events that can cause a shock.",
            "de": "Die Karte zeigt, dass eine Situation oder eine Lebensphase ein Ende nimmt. Auch symbolisiert sie schlimme Ereignisse, die einen Schreck auslösen können.",
            "pt": "Esta carta indica que uma situação ou uma fase da vida chega ao fim. Ela também simboliza eventos ruins, que podem causar susto.",
            "hu": "A kártya azt mutatja, hogy egy helyzet vagy életszakasz véget ér. Rossz eseményeket is szimbolizál, amelyek sokkot okozhatnak.",
        },
    ),
    28: Card(
        28,
        "sadness",
        {
            "en": "Light worry, sadness and dissatisfaction.",
            "de": "Leichten Kummer, Trauer und Unzufriedenheit.",
            "pt": "Preocupação, tristeza ou insatisfação.",
            "hu": "Könnyű aggodalom, szomorúság és elégedetlenség.",
        },
    ),
    29: Card(
        29,
        "fidelity",
        {
            "en": "This card symbolizes permanence and says that everyday life develops in the expected way without major changes. It also shows the people around you on whom you can rely. Near a person card, it says that the person stands by you.",
            "de": "Diese Karte symbolisiert Dauerhaftigkeit und besagt, dass der Alltag in gewohnter Weise verläuft und keine Veränderungen zu erwarten sind. Auch zeigt sie Deine Mitmenschen an, auf die Du Dich verlassen kannst. In der Nähe einer Personenkarte sagt sie aus, dass die Person zu Dir hält.",
            "pt": "Esta carta simboliza permanência e diz que a rotina desenvolve-se da maneira esperada sem grandes mudanças. Próxima a uma carta de pessoa, esta carta indica que essa pessoa é confiável.",
            "hu": "Ez a kártya állandóságot szimbolizál, és azt mondja, hogy a mindennapi élet a várt módon fejlődik, nagy változások nélkül. Azt is mutatja, hogy a környezetedben lévő emberekre számíthatsz. Egy személykártya közelében azt mondja, hogy az illető melletted áll.",
        },
    ),
    30: Card(
        30,
        "misfortune",
        {
            "en": "Possible dangers in everyday life. Often it is evident from the neighboring cards in which area of life this misfortune will occur.",
            "de": "Möglichen Gefahren im Alltag. Oft ist aus den Nachbarkarten ersichtlich, in welchem Lebensbereich sich dieses Unglück abspielen wird.",
            "pt": "Possível ameaça no cotidiano. As cartas vizinhas à esta mostrarão qual área da sua vida é afetada por esse infortúnio.",
            "hu": "Lehetséges veszélyek a mindennapi életben. Gyakran a szomszédos kártyákból kiderül, hogy az élet mely területén fog ez a balszerencse bekövetkezni.",
        },
    ),
    31: Card(
        31,
        "unexpectedJoy",
        {
            "en": "This card symbolizes pleasant surprises and a positive outcome.",
            "de": "Diese Karte symbolisiert angenehme Überraschungen und einen positiven Ausgang.",
            "pt": "Esta carta simboliza surpresas agradáveis e resultados positivos.",
            "hu": "Ez a kártya kellemes meglepetéseket és pozitív kimenetelt szimbolizál.",
        },
    ),
    32: Card(
        32,
        "annoyance",
        {
            "en": "This card shows conflicts. It also symbolizes irritability, nervousness and stress, which manifests itself through anger in various areas of life. Near a person card, it says that the person is easily irritable and quarrelsome.",
            "de": "Diese Karte zeigt Auseinandersetzungen an. Sie symbolisiert auch Gereiztheit, Nervosität und Stress, was sich durch Ärger in den einzelnen Lebensbereichen bemerkbar macht. In der Nähe einer Personenkarte sagt sie aus, dass die Person schnell reizbar und streitsüchtig ist.",
            "pt": "Esta carta mostra conflitos. Ela simboliza também agressividade, nervosismo ou estresse em alguma área da vida. Se próxima de uma carta de pessoa, ela mostra que essa pessoa é irritadiça e 'encrenqueira'.",
            "hu": "Ez a kártya konfliktusokat mutat. Irritálhatóságot, idegességet és stresszt is szimbolizál, amely dühként nyilvánul meg az élet különböző területein. Egy személykártya közelében azt mondja, hogy az illető könnyen ingerlékeny és veszekedős.",
        },
    ),
    33: Card(
        33,
        "loss",
        {
            "en": "This card shows losses. However, these do not necessarily have to be material or financial losses, but can also mean the loss of a partner, friends or joy of living. Near a person card, it indicates that the person is very careless.",
            "de": "Diese Karte zeigt Verluste an. Allerdings muss es sich hierbei nicht immer um materielle oder finanzielle Verluste handeln, sondern kann auch den Verlust der Partnerschaft, der Freunde oder auch der Lebensfreude symbolisieren. In der Nähe einer Personenkarte sagt sie aus, dass die Person sehr leichtsinnig ist.",
            "pt": "Esta carta mostra perdas. Essas perdas não estão necessariamente ligadas a bens materiais ou dinheiro, podendo também significar a perda do parceiro, de amigos ou da alegria de viver. Próxima a uma carta de pessoa, esta carta indica que essa pessoa é desleixada ou descuidada.",
            "hu": "Ez a kártya veszteségeket mutat. Ezek nem feltétlenül anyagi vagy pénzügyi veszteségek, hanem jelenthetik a partner, barátok vagy az életöröm elvesztését is. Egy személykártya közelében azt jelzi, hogy az illető nagyon gondatlan.",
        },
    ),
    34: Card(
        34,
        "widow",
        {
            "en": "Calm and solitude. Mostly it shows as a person card an older woman. It can be the mother, grandmother, aunt, older sister or older friend.",
            "de": "Ruhe und Einsamkeit. Meistens zeigt sie jedoch als Personenkarte eine ältere Frau. Es kann sich um die Mutter, Großmutter, Tante, ältere Schwester oder ältere Freundin handeln.",
            "pt": "Calma e solidão. Representa, como carta de pessoa, uma mulher mais velha, podendo ser a mãe, avó, tia, irmã mais velha ou parceira mais velha.",
            "hu": "Nyugalom és magány. Legtöbbször személykártyaként egy idősebb nőt mutat. Lehet az anya, nagymama, nagynéni, idősebb nővér vagy idősebb barátnő.",
        },
    ),
    35: Card(
        35,
        "widower",
        {
            "en": "Calm and solitude. Mostly it shows as a person card an older man. It can be the father, grandfather, uncle, older brother or older friend.",
            "de": "Ruhe und Einsamkeit. Meistens zeigt sie jedoch als Personenkarte einen älteren Mann. Es kann sich um den Vater, Großvater, Onkel, älteren Bruder, oder älteren Freund handeln.",
            "pt": "Calma e solidão. Representa, como carta de pessoa, um homem mais velho, podendo ser o pai, avô, tio, irmão mais velho ou parceiro mais velho.",
            "hu": "Nyugalom és magány. Legtöbbször személykártyaként egy idősebb férfit mutat. Lehet az apa, nagypapa, nagybácsi, idősebb testvér vagy idősebb barát.",
        },
    ),
}


def get_cards(card_ids: list[int]) -> list[Card]:
    """Get card objects by their IDs."""
    return [CARDS[id] for id in card_ids if id in CARDS]
