export interface Card {
  id: number;
  nameKey: string;
  shortMeaning: {
    en: string;
    de: string;
    pt: string;
    hu: string;
  };
}

export const CARDS: Card[] = [
  {
    id: 0,
    nameKey: 'constancy',
    shortMeaning: {
      en: '"Eye of God", means work and obligations, stability, permanence and security.',
      de: '"Auge Gottes", bedeutet Arbeit und Verpflichtungen, Stabilität, Beständigkeit und Sicherheit.',
      pt: '"Olho de Deus", significa trabalho e obrigações, estabilidade, permanência e segurança.',
      hu: '"Isten szeme", munkát és kötelezettségeket, stabilitást, állandóságot és biztonságot jelent.',
    },
  },
  {
    id: 1,
    nameKey: 'visit',
    shortMeaning: {
      en: 'Events, friends, parties and meetings with other people.',
      de: 'Ereignisse, Freunde, Partys und Treffen mit anderen Menschen.',
      pt: 'Eventos, amigos, festas e reuniões com outras pessoas.',
      hu: 'Események, barátok, bulik és találkozások más emberekkel.',
    },
  },
  {
    id: 2,
    nameKey: 'message',
    shortMeaning: {
      en: 'Communication, conversation.',
      de: 'Kommunikation, Gespräch.',
      pt: 'Comunicação, conversação.',
      hu: 'Kommunikáció, beszélgetés.',
    },
  },
  {
    id: 3,
    nameKey: 'letter',
    shortMeaning: {
      en: 'This card shows an important message, which can be a phone call, email, letter, or important document. It can also mean an invitation, secret or contract.',
      de: 'Diese Karte zeigt eine wichtige Nachricht, die ein Anruf, eine E-Mail, ein Brief oder ein wichtiges Dokument sein kann. Es kann auch eine Einladung, ein Geheimnis oder ein Vertrag bedeuten.',
      pt: 'Esta carta mostra uma mensagem importante, que pode ser um telefonema, E-Mail, carta, ou documento importante. Além disso pode significar um convite, segredo ou contrato.',
      hu: 'Ez a kártya fontos üzenetet mutat, ami lehet telefonhívás, e-mail, levél vagy fontos dokumentum. Emellett jelenthet meghívást, titkot vagy szerződést.',
    },
  },
  {
    id: 4,
    nameKey: 'thief',
    shortMeaning: {
      en: 'This card shows negative influences and tension generated by other people. If this card is near a card representing a person, it means you should be careful with them.',
      de: 'Diese Karte zeigt negative Einflüsse und Spannungen, die von anderen Menschen erzeugt werden. Wenn diese Karte in der Nähe einer Personenkarte liegt, bedeutet dies, dass Sie vorsichtig sein sollten.',
      pt: 'Esta carta mostra influências negativas e tensão geradas por outras pessoas. Se esta carta está próxima de uma carta representando uma pessoa, significa então que você deve tomar cuidado com ela.',
      hu: 'Ez a kártya más emberek által generált negatív befolyásokat és feszültséget mutat. Ha ez a kártya egy személyt reprezentáló kártya közelében van, azt jelenti, hogy óvatosnak kell lennie.',
    },
  },
  {
    id: 5,
    nameKey: 'jealousy',
    shortMeaning: {
      en: 'Jealousy, envy, and negative emotions in relationships.',
      de: 'Eifersucht, Neid und negative Emotionen in Beziehungen.',
      pt: 'Ciúmes, inveja e emoções negativas em relacionamentos.',
      hu: 'Féltékenység, irigység és negatív érzelmek a kapcsolatokban.',
    },
  },
  // Additional cards (6-35) - expanded from reference material
  { id: 6, nameKey: 'someMoney', shortMeaning: { en: 'Some money or financial opportunity.', de: 'Etwas Geld oder finanzielle Gelegenheit.', pt: 'Algum dinheiro ou oportunidade financeira.', hu: 'Egy kis pénz vagy pénzügyi lehetőség.' } },
  { id: 7, nameKey: 'falseness', shortMeaning: { en: 'Deception, lies, or false appearances.', de: 'Täuschung, Lügen oder falsche Erscheinungen.', pt: 'Engano, mentiras ou aparências falsas.', hu: 'Csalás, hazugságok vagy hamis megjelenések.' } },
  { id: 8, nameKey: 'enemy', shortMeaning: { en: 'An enemy or adversary in your path.', de: 'Ein Feind oder Gegner auf Ihrem Weg.', pt: 'Um inimigo ou adversário em seu caminho.', hu: 'Ellenség vagy ellenfél az Ön útján.' } },
  { id: 9, nameKey: 'joy', shortMeaning: { en: 'Happiness, celebration, and positive emotions.', de: 'Glück, Feier und positive Emotionen.', pt: 'Felicidade, celebração e emoções positivas.', hu: 'Boldogság, ünneplés és pozitív érzelmek.' } },
  { id: 10, nameKey: 'thought', shortMeaning: { en: 'Reflection, contemplation, and mental processes.', de: 'Reflexion, Kontemplation und mentale Prozesse.', pt: 'Reflexão, contemplação e processos mentais.', hu: 'Gondolkodás, elmélkedés és mentális folyamatok.' } },
  { id: 11, nameKey: 'priest', shortMeaning: { en: 'Spiritual guidance, wisdom, or authority figure.', de: 'Spirituelle Führung, Weisheit oder Autoritätsperson.', pt: 'Orientação espiritual, sabedoria ou figura de autoridade.', hu: 'Spirituális útmutatás, bölcsesség vagy tekintély.' } },
  { id: 12, nameKey: 'money', shortMeaning: { en: 'Financial abundance, wealth, or material success.', de: 'Finanzieller Überfluss, Reichtum oder materieller Erfolg.', pt: 'Abundância financeira, riqueza ou sucesso material.', hu: 'Pénzügyi bőség, gazdagság vagy anyagi siker.' } },
  { id: 13, nameKey: 'beloved', shortMeaning: { en: 'A loved one, romantic partner, or close relationship.', de: 'Ein geliebter Mensch, romantischer Partner oder enge Beziehung.', pt: 'Um ente querido, parceiro romântico ou relacionamento próximo.', hu: 'Szerető, romantikus partner vagy közeli kapcsolat.' } },
  { id: 14, nameKey: 'beloved', shortMeaning: { en: 'A loved one, romantic partner, or close relationship.', de: 'Ein geliebter Mensch, romantischer Partner oder enge Beziehung.', pt: 'Um ente querido, parceiro romântico ou relacionamento próximo.', hu: 'Szerető, romantikus partner vagy közeli kapcsolat.' } },
  { id: 15, nameKey: 'gift', shortMeaning: { en: 'A gift, surprise, or unexpected blessing.', de: 'Ein Geschenk, eine Überraschung oder unerwarteter Segen.', pt: 'Um presente, surpresa ou bênção inesperada.', hu: 'Ajándék, meglepetés vagy váratlan áldás.' } },
  { id: 16, nameKey: 'fortune', shortMeaning: { en: 'Good fortune, luck, and positive destiny.', de: 'Gutes Glück, Glück und positives Schicksal.', pt: 'Boa sorte, sorte e destino positivo.', hu: 'Jó szerencse, szerencse és pozitív sors.' } },
  { id: 17, nameKey: 'house', shortMeaning: { en: 'Home, family, stability, and domestic life.', de: 'Zuhause, Familie, Stabilität und häusliches Leben.', pt: 'Casa, família, estabilidade e vida doméstica.', hu: 'Otthon, család, stabilitás és családi élet.' } },
  { id: 18, nameKey: 'marriage', shortMeaning: { en: 'Marriage, union, partnership, or commitment.', de: 'Heirat, Vereinigung, Partnerschaft oder Engagement.', pt: 'Casamento, união, parceria ou compromisso.', hu: 'Házasság, egyesülés, partnerség vagy elköteleződés.' } },
  { id: 19, nameKey: 'hope', shortMeaning: { en: 'Hope, optimism, and positive expectations.', de: 'Hoffnung, Optimismus und positive Erwartungen.', pt: 'Esperança, otimismo e expectativas positivas.', hu: 'Remény, optimizmus és pozitív elvárások.' } },
  { id: 20, nameKey: 'child', shortMeaning: { en: 'A child, new beginnings, or innocence.', de: 'Ein Kind, neue Anfänge oder Unschuld.', pt: 'Uma criança, novos começos ou inocência.', hu: 'Gyermek, új kezdetek vagy ártatlanság.' } },
  { id: 21, nameKey: 'illness', shortMeaning: { en: 'Illness, health concerns, or physical challenges.', de: 'Krankheit, Gesundheitsbedenken oder körperliche Herausforderungen.', pt: 'Doença, preocupações com a saúde ou desafios físicos.', hu: 'Betegség, egészségügyi aggodalmak vagy fizikai kihívások.' } },
  { id: 22, nameKey: 'love', shortMeaning: { en: 'Love, romance, and deep emotional connection.', de: 'Liebe, Romantik und tiefe emotionale Verbindung.', pt: 'Amor, romance e conexão emocional profunda.', hu: 'Szerelem, romantika és mély érzelmi kapcsolat.' } },
  { id: 23, nameKey: 'officer', shortMeaning: { en: 'Authority, discipline, or official matters.', de: 'Autorität, Disziplin oder offizielle Angelegenheiten.', pt: 'Autoridade, disciplina ou assuntos oficiais.', hu: 'Tekintély, fegyelem vagy hivatalos ügyek.' } },
  { id: 24, nameKey: 'journey', shortMeaning: { en: 'A journey, travel, or movement in life.', de: 'Eine Reise, Reisen oder Bewegung im Leben.', pt: 'Uma jornada, viagem ou movimento na vida.', hu: 'Utazás, mozgás vagy életbeli változás.' } },
  { id: 25, nameKey: 'judge', shortMeaning: { en: 'Judgment, decision-making, or legal matters.', de: 'Urteil, Entscheidungsfindung oder rechtliche Angelegenheiten.', pt: 'Julgamento, tomada de decisão ou questões legais.', hu: 'Ítélet, döntéshozatal vagy jogi ügyek.' } },
  { id: 26, nameKey: 'desire', shortMeaning: { en: 'Desire, passion, or strong wishes.', de: 'Wunsch, Leidenschaft oder starke Wünsche.', pt: 'Desejo, paixão ou desejos fortes.', hu: 'Vágy, szenvedély vagy erős kívánságok.' } },
  { id: 27, nameKey: 'death', shortMeaning: { en: 'Endings, transformation, or significant change.', de: 'Enden, Transformation oder bedeutende Veränderung.', pt: 'Finais, transformação ou mudança significativa.', hu: 'Végek, átalakulás vagy jelentős változás.' } },
  { id: 28, nameKey: 'sadness', shortMeaning: { en: 'Sadness, grief, or emotional pain.', de: 'Traurigkeit, Trauer oder emotionaler Schmerz.', pt: 'Tristeza, luto ou dor emocional.', hu: 'Szomorúság, gyász vagy érzelmi fájdalom.' } },
  { id: 29, nameKey: 'fidelity', shortMeaning: { en: 'Loyalty, faithfulness, and commitment.', de: 'Loyalität, Treue und Engagement.', pt: 'Lealdade, fidelidade e compromisso.', hu: 'Hűség, lojalitás és elköteleződés.' } },
  { id: 30, nameKey: 'misfortune', shortMeaning: { en: 'Misfortune, bad luck, or difficult times.', de: 'Unglück, Pech oder schwere Zeiten.', pt: 'Infortúnio, má sorte ou tempos difíceis.', hu: 'Balszerencse, nehéz idők vagy csapások.' } },
  { id: 31, nameKey: 'unexpectedJoy', shortMeaning: { en: 'Unexpected joy, pleasant surprises, or sudden happiness.', de: 'Unerwartete Freude, angenehme Überraschungen oder plötzliches Glück.', pt: 'Alegria inesperada, surpresas agradáveis ou felicidade súbita.', hu: 'Váratlan öröm, kellemes meglepetések vagy hirtelen boldogság.' } },
  { id: 32, nameKey: 'disgust', shortMeaning: { en: 'Disgust, repulsion, or strong negative feelings.', de: 'Ekel, Abstoßung oder starke negative Gefühle.', pt: 'Desgosto, repulsa ou sentimentos negativos fortes.', hu: 'Undor, taszítás vagy erős negatív érzelmek.' } },
  { id: 33, nameKey: 'loss', shortMeaning: { en: 'Loss, separation, or letting go.', de: 'Verlust, Trennung oder Loslassen.', pt: 'Perda, separação ou deixar ir.', hu: 'Veszteség, szétválás vagy elengedés.' } },
  { id: 34, nameKey: 'widow', shortMeaning: { en: 'Widowhood, loss of partner, or independence.', de: 'Witwenschaft, Verlust des Partners oder Unabhängigkeit.', pt: 'Viuvez, perda do parceiro ou independência.', hu: 'Özvegység, partner elvesztése vagy függetlenség.' } },
  { id: 35, nameKey: 'widower', shortMeaning: { en: 'Widowerhood, loss of partner, or independence.', de: 'Witwerschaft, Verlust des Partners oder Unabhängigkeit.', pt: 'Viuvez, perda do parceiro ou independência.', hu: 'Özvegyi állapot, partner elvesztése vagy függetlenség.' } },
];

